export type IntroductionPage = { title: string; paragraphs: string[] };
export type AnswerOption = { id: string; text: string };
export type Question = { id: string; prompt: string; options: AnswerOption[] };
export type Category = { name: string; prompt: string; description: string; questions?: Question[] };

export const introductionPages: IntroductionPage[] = [
  { title: "Maybe you're here because ...", paragraphs: ["Maybe you're here because you're trying to understand yourself a little better.", "Maybe you know you want something from your life, but you haven't figured out exactly what that something is yet.", "I've been there too."] },
  { title: "Why I created Nexus", paragraphs: ["When I was around 16 or 17, I went through a period where I felt genuinely unsure about what I should do next. I had questions about myself, my future, and what I was actually meant to pursue.", "So I started looking inward.", "I paid attention to what interested me, what I naturally enjoyed, what I was good at, what mattered to me, and what kind of future actually felt right.", "That process eventually helped me find a direction: mechatronics engineering.", "But the real breakthrough wasn't simply choosing a career. It was understanding myself well enough to recognize a direction that felt right for me.", "That's where Nexus began."] },
  { title: "Nexus isn't here to label you.", paragraphs: ["Nexus isn't here to tell you who you are.", "It isn't a personality test that puts you into a category.", "And it isn't here to give you an identity after a few questions.", "Instead, Nexus looks for patterns across your answers: the signals that appear repeatedly and connect with each other.", "The goal is to help you see something that may already be there, but that you haven't clearly seen yet."] },
  { title: "So, be honest..", paragraphs: ["Don't choose the answer that sounds impressive.", "Don't choose what you think you should be.", "Choose what actually feels true to you.", "Because Nexus can only reflect what you give it.", "The more honestly you answer, the more honestly Nexus can reflect your patterns back to you."] },
  { title: "Your answers are yours.", paragraphs: ["This experience is designed for honest self-reflection.", "Your answers are used to understand the patterns you choose to share with Nexus and to build your personal results.", "Nexus is not here to judge you, publicly identify you, or define you without your participation.", "Your reflections should feel like a private space to understand yourself more clearly."] },
  { title: "Your journey", paragraphs: ["You'll explore eight parts of yourself:"] },
  { title: "At the end of your journey", paragraphs: ["You won't simply receive a label.", "You'll receive a clearer picture of yourself.", "Expected output", "YOUR PERSONAL PATTERNS\nYOUR DIRECTION\nYOUR FOCUS\nYOUR SKILL\nYOUR HABITS\nYOUR 30-DAY GOAL\nYOUR BARRIER PLAN\nYOUR REFLECTION PLAN\nYOUR MISSION"] },
  { title: "Begin with honesty", paragraphs: ["Take your time.", "There is no \"right\" version of you to discover here.", "We're not trying to create a better version of you.", "We're trying to understand the real one."] },
  { title: "Let's begin", paragraphs: ["Start wherever you are.", "Answer honestly, and let the patterns reveal themselves over time."] },
];

export const categories: Category[] = [
  { name: "Identity", prompt: "Who am I?", description: "Let's start with you.\nBefore we explore where you want to go, let's understand how you see yourself today.\nThis part is about the way you naturally describe yourself, the qualities you recognize in yourself, and the way you experience who you are.\nThere isn't a version of you that you're supposed to choose.\nJust answer what feels true." },
  { name: "Strengths", prompt: "What comes naturally to me?", description: "" }, { name: "Interests", prompt: "What draws my attention?", description: "" }, { name: "Values", prompt: "What matters to me?", description: "" }, { name: "Personality", prompt: "How do I think and act?", description: "" }, { name: "Barriers", prompt: "What's holding me back?", description: "" }, { name: "Vision", prompt: "What future do I want?", description: "" }, { name: "Growth", prompt: "Where do I want to go next?", description: "" },
];

export const identityQuestion = { prompt: "When do you feel most like yourself?", options: ["When I'm creating or building something", "When I'm learning something new", "When I'm helping someone", "When I'm completely alone with my thoughts", "When I'm with people who truly understand me", "When I'm solving a difficult problem", "When I'm exploring or experiencing something new"].map((text, index): AnswerOption => ({ id: String.fromCharCode(97 + index), text })) };