import React from "react";
import { Image, SafeAreaView, ScrollView, StyleSheet, Text } from "react-native";
import AnswerOption from "../components/AnswerOption";
import NexusButton from "../components/NexusButton";
import ProgressBar from "../components/ProgressBar";
import TextAnswerInput from "../components/TextAnswerInput";
import { Category, Question, identityQuestion } from "../constants/discoveryContent";
import { colors } from "../constants/theme";
type Props = { category: Category; categoryIndex: number; question?: Question; selected: string | null; custom: string; onSelect: (id: string) => void; onCustomChange: (value: string) => void; onContinue: () => void; onBack: () => void };
export default function QuestionScreen({ category, question = { id: "identity-1", prompt: identityQuestion.prompt, options: identityQuestion.options }, selected, custom, onSelect, onCustomChange, onContinue, onBack }: Props) { const customMode = selected === "custom"; const enabled = selected !== null && (!customMode || custom.trim().length > 0); return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text onPress={onBack} style={styles.back}>← Back</Text><Image source={require("../assets/branding/nexus-wordmark.jpg")} style={styles.wordmark} resizeMode="contain" /><Text style={styles.category}>{category.name.toUpperCase()}</Text><Text style={styles.meta}>Question 01 of 08</Text><ProgressBar progress={1 / 8} width={310} /><Text style={styles.question}>{question.prompt}</Text>{customMode ? <TextAnswerInput value={custom} onChangeText={onCustomChange} /> : question.options.map((option) => <AnswerOption key={option.id} label={option.id.toUpperCase()} text={option.text} selected={selected === option.id} onPress={() => onSelect(option.id)} />)}<AnswerOption label="H" text="Write my own answer" selected={customMode} onPress={() => onSelect("custom")} />{customMode && <Text style={styles.helper}>There's no right answer.{"\n"}Take your time.</Text>}<NexusButton title="Continue  →" disabled={!enabled} onPress={onContinue} /></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 64, paddingTop: 30 }, back: { fontSize: 18, color: colors.mutedText }, wordmark: { width: 208, height: 68 }, category: { marginTop: 105, fontSize: 32, fontWeight: "600", color: colors.primary }, meta: { marginTop: 18, marginBottom: 28, fontSize: 20, color: colors.mutedText }, question: { marginTop: 55, marginBottom: 70, fontSize: 28, lineHeight: 36, fontWeight: "700", color: colors.deepInk }, helper: { margin: 28, fontSize: 20, lineHeight: 30, color: colors.mutedText }, });